spring.application.name=tienda_virtual
# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tienda_virtual
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8443

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=rodrigo33
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

mercadopago.access.token=APP_USR-7753971265016388-021215-00acedd2bb909f0330f7654eff36d06d-3200707522
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

